export * as distribution from './distribution/index';
export * as bandwidth from './bandwidth';
export * as distance from './distance';
export { default as erf } from './erf';
export { default as hcluster } from './hcluster';
export { default as iqr } from './iqr';
export { default as kde } from './kde';
export * as kernel from './kernel';
export { default as kmeans } from './kmeans';
export { default as loess } from './loess';
export { default as mean } from './mean';
export { default as median } from './median';
export { default as mode } from './mode';
export { default as phi } from './phi';
export { default as quantiles } from './quantiles';
export { default as variance } from './variance';
